### ISSUE TITLE
[BUG] Not able to install via brew

### ISSUE THREAD

**Issue by anuj-panwar-maersk** [nao1215/leadtime#16]
**Describe the bug**
Not able to install via brew

**To Reproduce**

% brew install nao1215/tap/leadtime
Error: No available formula with the name "nao1215/tap/leadtime". Did you mean nao1215/tap/jose?
In formula file: /opt/homebrew/Library/Taps/nao1215/homebrew-tap/Formula/leadtime.rb
Expected to find class Leadtime, but only found: LeadTime.

**Expected behavior**
Should get install

**Desktop (please complete the following information):**
 - OS: Mac 13.1

**Comment by krisquigley** [comment]
I'm also facing this issue:

```
==> Tapping nao1215/tap
Cloning into '/opt/homebrew/Library/Taps/nao1215/homebrew-tap'...
remote: Enumerating objects: 269, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (90/90), done.
Receiving objects: 100% (269/269), 51.87 KiB | 1.62 MiB/s, done.
remote: Total 269 (delta 57), reused 0 (delta 0), pack-reused 179 (from 2)
Resolving deltas: 100% (129/129), done.
Tapped 9 formulae (22 files, 77.4KB).
 ~/workspace   brew install nao1215/tap/leadtime
Warning: No available formula or cask with the name "nao1215/tap/leadtime". Did you mean nao1215/tap/sqly?
```
